import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '../component/Header'
import Banner from '../component/Banner'
import {sanityClient,urlFor} from '../sanity'
import { post } from '@/type'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

interface Props {
  post: [post]
}

export default function Home({post}:Props) {

  // console.log(post);
  

  return (
    <>
      <Head>
        <title>Medium Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div >
        <Header/>
        <Banner/>
        <div className='flex justify-between max-w-7xl p-5 mx-auto '>
          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 md:gap-6 p-2 md:p-6'> 
            {post.map((post)=>{
              return <Link key={post._id} href={`/post/${post.slug.current}`}>
                        <div className='border rounded-lg group overflow-hidden'>
                            <img className=' h-60 w-full object-cover group-hover:scale-105 transition-transform duration-200 ease-in-out' src={urlFor(post.mainImage).url()!} alt="" />
                            <div className='flex justify-between p-5'>
                              <div >
                                <p className='text-lg font-bold'>{post.title}</p>
                                <p className='text-xs'>{post.description} by {post.author.name}</p>
                              </div>
                              <img className='h-16 w-16 rounded-full'  src={urlFor(post.author.image).url()!}/>
                            </div>
                        </div>
                     </Link>
            })
            }
          </div>
        </div>
      </div>
    </>
  )
}

export const getServerSideProps = async ()=> {

  const query = `*[_type=="post"]{
    _id,
    title,  
    slug,
      
    author->{
      name,
      image
    },
    description,
    mainImage
  }`

  const post = await sanityClient.fetch(query)
  return { props:{post}}

} 
